name: Snyk OSS Scan with PR Comment

on:
  pull_request:

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  snyk-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      - name: Run Snyk test and save JSON
        run: snyk test --json | tee snyk-results.json || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Create PR comment with Snyk summary
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const results = JSON.parse(fs.readFileSync('snyk-results.json', 'utf8'));
            const vulns = results.vulnerabilities || [];

            if (vulns.length === 0) {
              commentBody = "✅ No Snyk vulnerabilities found!";
            } else {
              const summary = vulns
                .slice(0, 10)
                .map(v => `- **${v.severity.toUpperCase()}**: \`${v.packageName}@${v.version}\` - ${v.title}`)
                .join('\n');
              commentBody = `### 🔒 Snyk Vulnerability Summary\n\n${summary}\n\n_Only showing top 10._`;
            }

            const pr = context.payload.pull_request.number;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr,
              body: commentBody
            });
