name: Snyk Full Security Scan

on:
  push:
  pull_request:

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install
          npm install http-signature

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      - name: Snyk OSS scan (dependencies)
        run: snyk test --sarif-file-output=snyk-oss.sarif --all-projects --detection-depth=2 --exclude=node_modules
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Snyk Code scan (static analysis)
        run: snyk code test --sarif > snyk-code.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Sanitize SARIF files (OSS + Code)
        run: |
          for file in snyk-oss.sarif snyk-code.sarif; do
            if [ -f "$file" ]; then
              echo "Sanitizing $file"
              node -e "
              const fs = require('fs');
              const path = '$file';
              const sarif = JSON.parse(fs.readFileSync(path, 'utf8'));
              let fixed = false;

              for (const run of sarif.runs || []) {
                const rules = run.tool?.driver?.rules || [];
                for (const rule of rules) {
                  rule.properties = rule.properties || {};
                  if (typeof rule.properties.securitySeverity !== 'number') {
                    rule.properties.securitySeverity = 3.0;
                    fixed = true;
                  }
                }
              }

              if (fixed) {
                fs.writeFileSync(path, JSON.stringify(sarif, null, 2));
                console.log('✅ $file sanitized and saved.');
              } else {
                console.log('✅ $file already clean.');
              }
              "
            fi
          done

      - name: Upload OSS SARIF to GitHub Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-oss.sarif

      - name: Upload Code SARIF to GitHub Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
