name: Snyk Full Security Scan

on:
  push:
  pull_request:

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install
          npm install http-signature

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      - name: Snyk OSS scan (dependencies)
        run: snyk test --sarif-file-output=snyk-oss.sarif --all-projects --detection-depth=2 --exclude=node_modules
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Code scan (static analysis)
        run: snyk code test --sarif > snyk-code.sarif
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Fix undefined severity in OSS SARIF
        run: sed -i 's/"security-severity": "undefined"/"security-severity": 0/g' snyk-oss.sarif

      - name: "Debug: List SARIF files"
        run: |
          echo "--- snyk-oss.sarif ---"
          grep -i securitySeverity snyk-oss.sarif || echo "None found"
          echo "--- snyk-code.sarif ---"
          grep -i securitySeverity snyk-code.sarif || echo "None found"

      - name: Upload OSS SARIF to GitHub Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-oss.sarif

      - name: Upload Code SARIF to GitHub Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
