name: Snyk Security Scan

on:
  push:
  pull_request:

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install Snyk CLI
      uses: snyk/actions/setup@master

    - name: Run Snyk test
      run: snyk test --all-projects --detection-depth=2 --exclude=node_modules
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true
  

    - name: Monitor with Snyk (optional)
      run: snyk monitor --all-projects --detection-depth=2 --exclude=node_modules
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Generate SARIF report
      run: snyk test --sarif-file-output=snyk.sarif --all-projects --detection-depth=2 --exclude=node_modules
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Upload SARIF to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif
